
services:
    mailpit:
        image: 'axllent/mailpit:latest'
        restart: unless-stopped
        volumes:
            - ./docker/mailpit:/data
        ports:
            - "8003:1025"
            - "8100:8025"
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATABASE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1

    redis:
        image: "redis:alpine"
        restart: unless-stopped
        command: redis-server
        ports:
            - "6379:6379"
        volumes:
            - ./docker/redis/data:/data

    mariadb:
        image: 'mariadb:11.0'
        working_dir: /application
        restart: unless-stopped
        volumes:
            - ./docker/mariadb:/var/lib/mysql
            - ./shared:/var/shared
        environment:
            - MYSQL_ROOT_PASSWORD=root_password
            - MYSQL_DATABASE=trade_db
            - MYSQL_USER=trade_app
            - MYSQL_PASSWORD=trade_password
            - MARIADB_AUTO_UPGRADE=1
        ports:
            - '3306:3306'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./shared:/var/shared
        environment:
            PMA_HOST: mariadb
            MYSQL_ROOT_PASSWORD: "root_password"
            UPLOAD_LIMIT: 4G

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        restart: unless-stopped
        volumes:
            - './app:/application'
            - ./logs/nginx:/var/log/nginx
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '80:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - './app:/application'
            - ./shared:/var/shared
            - ./logs/app:/application/var/log
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/cli/conf.d/99-overrides.ini'
