nelmio_api_doc:
    use_validation_groups: true
    documentation:
#        servers:
#            - url: http://api.example.com/unsafe
#              description: API over HTTP
#            - url: https://api.example.com/secured
#              description: API over HTTPS
        info:
            title: My App
            description: This is an awesome app!
            version: 1.0.0
            x-build: #CommitHash
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: [ ]
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
